### PR TITLE
Multiprocessing

### PR DESCRIPTION
**Pull request by firefart**
this makes it easier to see the changes and discuss them.

### CODE REVIEW

**Comment by FireFart** [comment]
BTW travis is currently failing

**Comment by andreashappe** [comment]
that's why I haven't merged it yet (and haven't created a MR) -- need to adopt two test cases to the new API.

If you want to, you can pull the multiprocessing branch to get the new version. I hope I'll get to fixing the test cases on the weekend -- next week I'm abroads so that's my deadline.

**Comment by andreashappe** [comment]
okay, do you want to test this on your production machine?

meh. it works on my Ubuntu machine but I do have a build problem on travis-ci (with the sqlite version). Heh on my Fedora 23 machine it does only work with a batchsize of ~50 (due to the sqlite compile options).

still not really comfy to pull this into master, but if you could have a look that would be good for me.

I think we could still do the multi-process multi-db connection thing (and switch the current implementation from a ThreadPool to a ProcessPool). Still feels not really clean, but I'm done fighting against python (;

**Comment by FireFart** [comment]
wanted to try it but the importer only takes a filelist as an argument - for a good test there are too many arguments. Is there a way to also specify a directory and the importer loops all files and subdirectories? Would make it a lot easier.

**Comment by andreashappe** [comment]
could you check out the [directories branch](https://github.com/andreashappe/mod_security_importer/commits/directories). It's very basic (and ugly, i need a function that splits a list of files into files and directories).

I'm thinking about either creating an Iterator over os.walk (so that I can map the import function over it) or give up and move the os.walk into an python process of it's own, move the results into a queue and map/call a function over the pool. Must look into python's concurrent futures. That's a rather standard use caes.. there should be a more elegant way of doing this.

Hm. could you do your postgres testcase magic again for the multiprocessing branch (and switch the failing testcases to postgres)? Then I would merge this change-set.

**Comment by FireFart** [comment]
I just tried your changes from the directories branch with sqlite3 on my laptop:

y4qsvvd

as you can see, IO and CPU are really low so I think there is still some bug anywhere in the code. Or shouldn't it go to full CPU-utilization yet?

**Comment by FireFart** [comment]
also:
```
(env) [firefart@arch bin]$ ./import --import-parts test.sqlite3 ../../mod_sec_logs/
also adding parts!
Traceback (most recent call last):
  File "./import", line 5, in <module>
    import_log_to_database()
  File "/home/firefart/mod_security_importer/env/lib/python3.5/site-packages/log_importer-0.1-py3.5.egg/log_importer/importer.py", line 130, in import_log_to_database
  File "/home/firefart/mod_security_importer/env/lib/python3.5/site-packages/log_importer-0.1-py3.5.egg/log_importer/importer.py", line 76, in forward_to_db
  File "/home/firefart/mod_security_importer/env/lib/python3.5/site-packages/log_importer-0.1-py3.5.egg/log_importer/importer.py", line 76, in <listcomp>
KeyError: 'file'
```

**Comment by andreashappe** [comment]
Hm. okay, so we currently process 12.5 MByte/sec of incoming log data (that's the most meaningful metric). What rate is expected for the hardware?

A couple of questions (sorry for bothering that much, but I need a better feel for the system):

* could you run the test with postgres and post the summed read I/O rate?
* what was the summed read I/O rate with your initial multi-process tool?
* could you exchange the ProcessPoolExecutor (importer.py, line 124) with a ThreadPoolExecutor. This should switch to a single process model --- what's the read I/O rate you get with this solution.

If you comment out the "forward_to_db" call in importer.py line 126 (or exchange it with a pass) then we would have a better grasp of the database-side overhead.

I've opened a bug report for the parsing issue

**Comment by FireFart** [comment]
Here is a screenshot of another small python project using postgres and multiprocessing.
test

So there is a lot more disk io :) (I don't know the actual numbers)

How do I run it in postgres mode? Do I have to edit a file or is there a hidden switch?

**Comment by andreashappe** [comment]
you're comparing apples with pears. The postgres operation operates on a single large file (i.e. OS caching works) -- while we have to read thousands of small files. That's why I wanted the data with a one-process model (point 3) to see, how much file I/O a single process can get with optimum cache I/O cache utilization.

On my laptop (am currently in Spain, so don't have a ``better'' system) the amortized latency per processed file/incident is roughly 0.9ms including all file and db access. This is on a SSD and the file should also be cached by the OS; on a harddrive this is only possible if files are already within the cache (otherwise I'd assume 8-9ms seek time, on average 50% seek needed -> 4-4.5ms/file already for I/O seek). If caching is a a problem then we wouldn't get more than 200 processed incidents per second (and even fewer if we add more processes as the disk I/O is the limiting factor).

The postgres switch would be to state a full sqlalchemy string instead of the db.sqlite-path, i.e. postgres://modsec:modsec@localhost/modsec. With that the db write proportion of the import should be moved to postgres. On my system there was not much improvement through that (as sqlite was used inline and in the same process; thus used less process-I/O and context switches).

**Comment by andreashappe** [comment]
okay, I'll pull this into master. It improves performance on my two testing machines.

@FireFart : I would be really interested into the postgresql and the single-threaded performance measurement. This should be future performance improvements. I've also added a simple KeyError catcher, if you find the error, please add information to the bug report.

**Pull request merged**
