### PR TITLE
use multiprocessing

### PR DESCRIPTION
**Pull request by FireFart**
* switch to psql and use psql datatypes
* use multiprocessing
* some code styling

Need to do some testing tomorrow with "real world data"

### CODE REVIEW

**Comment by andreashappe** [comment]
Hi,
thanks for the PR as well as the "fix travis" update.

So far, I like the patch but I would like to change it a bit. Based on your patch I can do this in the next couple of days (if it's not time-critical).

I'd:

1. split up the patches into three
2. patch #1: style fixes (100%  yours)
3. patch #2: multiworker (100% yours)
4. patch #3: add postgres support. Will do this differently; in a way that postgres or sqlite would be supported. Not sure If I'll automatically test the postgres cases with travis-ci

If you're faster than me, feel free to split up the patches (;

cheers and thanks again, Andreas

**Comment by FireFart** [comment]
@andreashappe travis fixed :)

Sqlite does not work well with multiple threads because it's file based and designed for one concurrent connection at a time. So if you want to do some things in parallel you need mysql or postgres. Postgres has a special datatype for storing ip adresses so you can do netmask calculations in your database statements.

**Comment by FireFart** [comment]
@andreashappe see #2

**Comment by andreashappe** [comment]
please see https://github.com/andreashappe/mod_security_importer/tree/multiprocessing

still missing: the inet datatype for ips.

**Pull request closed without merging**
